{
  boolean caughtError=false;
  try {
    op.waitForLocallyCompleted();
  }
 catch (  ForeignException fe) {
    caughtError=true;
  }
  Mockito.verify(op,prepare).acquireBarrier();
  Mockito.verify(op,commit).insideBarrier();
  assertEquals("Operation error state was unexpected",opHasError,op.getErrorCheckable().hasException());
  assertEquals("Operation error state was unexpected",opHasError,caughtError);
}
